# Generated by Django 5.0 on 2023-12-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0002_sumparticipations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='percentage',
            field=models.FloatField(null=True),
        ),
    ]
